const views=["home","prompt","presets","recorder","help","transcribe"];
const $=(q)=>document.querySelector(q);
function show(view){views.forEach(v=>{const el=$(`#view-${v}`);if(!el)return;el.classList.toggle("hidden",v!==view)});document.querySelectorAll(".tab").forEach(b=>{b.classList.toggle("active",b.dataset.view===view)});window.scrollTo(0,0)}
document.querySelectorAll(".tab").forEach(b=>{b.addEventListener("click",()=>show(b.dataset.view))});
document.querySelectorAll("[data-goto]").forEach(b=>{b.addEventListener("click",()=>show(b.dataset.goto))});
function buildPrompt(d){const lines=[`MODE: ${d.mode}`,`LANGUAGE: ${d.language}`,`THEME: ${d.theme}`,`STYLE PACK: ${d.stylePack}`,`TEMPO: ${d.tempo||""}`.trim(),`RHYTHM: ${d.rhythm||""}`.trim(),`INSTRUMENTS: ${d.instruments||""}`.trim(),`VOCAL: ${d.vocal}`,`DURATION: ${d.duration||"Unlimited"}`,`PREVIEW FIRST: ${d.previewFirst}`,`LYRICS RULE: ${d.lyricsRule||""}`.trim(),`REFERENCE: ${d.reference||""}`.trim()].filter(Boolean);return lines.join("\n")}
$("#promptForm").addEventListener("submit",(e)=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());$("#promptOut").value=buildPrompt(d)});
$("#btnCopy").addEventListener("click",async()=>{const t=$("#promptOut").value.trim();if(!t)return;await navigator.clipboard.writeText(t);alert("Prompt copied!")});
$("#btnClear").addEventListener("click",()=>{$("#promptOut").value=""});
const builtInPresets=[{id:"holi-marwadi",title:"Rajasthani/Marwadi — Fagun Holi Dhamal",meta:"118 BPM • Dhamal 4/4 • Call-response",data:{mode:"Holi Dhamal",language:"Marwadi",theme:"Fagun Holi masti, crowd singalong",stylePack:"Rajasthani-Marwadi (Chang Dhamal)",tempo:"118 BPM",rhythm:"Dhamal 4/4 swing + Chang accents",instruments:"Chang, Dholak, Khartal, Algoza, Harmonium",vocal:"AI Female Folk + Chorus",duration:"Unlimited",previewFirst:"YES (3 previews, 20 sec)",lyricsRule:"Clear pronunciation, short hook, call-response",reference:"https://www.youtube.com/watch?v=Gz_j8pPvjfI"}},{id:"bhajan-pure",title:"Pure Bhajan — Harmonium+Tabla+Tanpura",meta:"76 BPM • Keherwa soft • Hindi",data:{mode:"Bhajan",language:"Hindi",theme:"Shri Ram / Krishna naam bhajan",stylePack:"Bhajan-Pure",tempo:"76 BPM",rhythm:"Keherwa (soft)",instruments:"Harmonium, Tabla, Tanpura, Manjira",vocal:"My Recorded Voice",duration:"Unlimited",previewFirst:"YES (3 previews, 20 sec)",lyricsRule:"Clear words, slow singable melody",reference:""}},{id:"instrumental",title:"Instrumental Only — Acoustic/Cinematic",meta:"92 BPM • No vocal",data:{mode:"Instrumental",language:"Hindi",theme:"Instrumental only, clean mix",stylePack:"Instrumental-Core",tempo:"92 BPM",rhythm:"4/4 steady",instruments:"Guitar/Piano, soft percussion, strings",vocal:"None",duration:"Unlimited",previewFirst:"YES (3 previews, 20 sec)",lyricsRule:"N/A",reference:""}}];
function renderPresets(){const list=$("#presetList");list.innerHTML="";builtInPresets.forEach(p=>{const div=document.createElement("div");div.className="presetItem";div.innerHTML=`<h3>${p.title}</h3><div class="meta">${p.meta}</div><div class="rowbtn"><button class="btn" data-load="${p.id}">Load</button><button class="btn ghost" data-gen="${p.id}">Generate</button></div>`;list.appendChild(div)});list.querySelectorAll("[data-load]").forEach(b=>{b.addEventListener("click",()=>{const p=builtInPresets.find(x=>x.id===b.dataset.load);fillForm(p.data);show("prompt")})});list.querySelectorAll("[data-gen]").forEach(b=>{b.addEventListener("click",()=>{const p=builtInPresets.find(x=>x.id===b.dataset.gen);fillForm(p.data);$("#promptOut").value=buildPrompt(p.data);show("prompt")})})}
function fillForm(d){const f=$("#promptForm");for(const[k,v]of Object.entries(d)){const el=f.querySelector(`[name="${k}"]`);if(el)el.value=v}}
function getMyPresets(){try{return JSON.parse(localStorage.getItem("myPresets")||"[]")}catch{return[]}}
function setMyPresets(arr){localStorage.setItem("myPresets",JSON.stringify(arr))}
function renderMyPresets(){const list=$("#myPresetList");const arr=getMyPresets();list.innerHTML=arr.length?"":`<div class="muted">No saved presets yet.</div>`;arr.forEach((p,idx)=>{const div=document.createElement("div");div.className="presetItem";div.innerHTML=`<h3>${p.title}</h3><div class="meta">${p.meta}</div><div class="rowbtn"><button class="btn" data-load="${idx}">Load</button><button class="btn ghost" data-del="${idx}">Delete</button></div>`;list.appendChild(div)});list.querySelectorAll("[data-load]").forEach(b=>{b.addEventListener("click",()=>{const p=getMyPresets()[+b.dataset.load];fillForm(p.data);$("#promptOut").value=buildPrompt(p.data);show("prompt")})});list.querySelectorAll("[data-del]").forEach(b=>{b.addEventListener("click",()=>{const arr=getMyPresets();arr.splice(+b.dataset.del,1);setMyPresets(arr);renderMyPresets()})})}
$("#btnSavePreset").addEventListener("click",()=>{const f=$("#promptForm");const d=Object.fromEntries(new FormData(f).entries());const title=prompt("Preset ka naam?");if(!title)return;const meta=`${d.mode} • ${d.language} • ${d.tempo||""}`.trim();const arr=getMyPresets();arr.unshift({title,meta,data:d});setMyPresets(arr);alert("Saved!");renderMyPresets()});
renderPresets();renderMyPresets();
let deferredPrompt=null;
window.addEventListener('beforeinstallprompt',(e)=>{e.preventDefault();deferredPrompt=e;$("#btnInstall").style.display="inline-block"});
$("#btnInstall").addEventListener("click",async()=>{if(!deferredPrompt){alert("iPhone: Safari → Share → Add to Home Screen");return}deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null});
let mediaRecorder,chunks=[];
const btnRec=$("#btnRec"),btnStop=$("#btnStop"),btnDl=$("#btnDownload"),playback=$("#playback");
btnRec.addEventListener("click",async()=>{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=(e)=>chunks.push(e.data);mediaRecorder.onstop=()=>{const blob=new Blob(chunks,{type:"audio/webm"});const url=URL.createObjectURL(blob);playback.src=url;btnDl.href=url;btnDl.style.pointerEvents="auto";btnDl.style.opacity="1"};mediaRecorder.start();btnRec.disabled=true;btnStop.disabled=false});
btnStop.addEventListener("click",()=>{if(!mediaRecorder)return;mediaRecorder.stop();btnRec.disabled=false;btnStop.disabled=true});
const transcribePresets=[{id:"folk",label:"🪘 Folk/Regional",genre:"Regional Folk",instruments:"Dholak, Harmonium, Flute, Chorus"},{id:"hindustani",label:"🎻 Hindustani Classical",genre:"Hindustani Classical",instruments:"Sitar, Tabla, Tanpura, Harmonium"},{id:"carnatic",label:"🎵 Carnatic Classical",genre:"Carnatic Classical",instruments:"Veena, Mridangam, Violin, Flute"},{id:"qawwali",label:"🕌 Qawwali/Sufi",genre:"Qawwali/Sufi",instruments:"Harmonium, Tabla, Dholak, Male vocals, Chorus"},{id:"bollywood",label:"🎬 Bollywood/Filmi",genre:"Bollywood",instruments:"Orchestra, Synth, Tabla, Lead vocal"},{id:"jazz",label:"🎷 Jazz/Blues",genre:"Jazz/Blues",instruments:"Piano, Bass, Drums, Trumpet, Sax"},{id:"classical_west",label:"🎼 Western Classical",genre:"Western Classical",instruments:"Piano, Violin, Cello, Orchestra"},{id:"flamenco",label:"💃 Flamenco/Latin",genre:"Flamenco/Latin",instruments:"Guitar, Cajon, Violin, Vocals"},{id:"hiphop",label:"🎤 Hip-Hop/R&B",genre:"Hip-Hop/R&B",instruments:"808 Bass, Drum machine, Synth, Vocal"},{id:"edm",label:"🎧 EDM/Electronic",genre:"EDM/Electronic",instruments:"Synth lead, Sub bass, Drum machine, Pads"},{id:"reggae",label:"🌴 Reggae/Afrobeat",genre:"Reggae/Afrobeat",instruments:"Bass, Drums, Guitar, Keyboard, Vocals"},{id:"world",label:"🌍 World Music (All)",genre:"World Music",instruments:"Auto-detect all"}];
function buildTranscribePrompt(url,genre,instruments,key,tempo){return `🎵 UNIVERSAL MUSIC TRANSCRIPTION PROMPT\n==========================================\nINPUT:\n• URL: ${url}\n• Genre: ${genre}\n• Instruments: ${instruments}\n• Key: ${key||"Auto-detect"}\n• Tempo: ${tempo||"Auto-detect BPM"}\n==========================================\nDELIVER:\nA) SUMMARY\n1. Title + Source\n2. Detected Key (enharmonic spellings)\n3. BPM + tempo changes with timestamps\n4. Time signature(s) with timestamps\n5. Arrangement map: Intro/Verse/Chorus/Bridge/Outro\n\nB) MELODY & HARMONY\n1. Melody note-by-note with octave (e.g. E4 D#4 F#4)\n2. Chord progression per measure: ||: Am | G | F | E :||\n3. Roman numeral analysis\n4. Note sequence with timestamps + confidence score\n\nC) INSTRUMENTATION\nFor each instrument:\n• Name + Role\n• 1-2 bar rhythmic loop\n• Timbre + MIDI mapping\n\nD) PERCUSSION/RHYTHM\n• Bar-by-bar groove\n• Accents, ghost notes, fills\n• 4-bar loop\n\nE) ARRANGEMENT NOTES\n• Entry/exit timestamps\n• Dynamics: p/mp/mf/f\n• Voicing suggestions\n\nF) DAW RECREATION\n• Channels, pan, volume\n• VST/sample suggestions\n• FX settings\n\nG) CONFIDENCE SCORES\n• Per-section pitch accuracy (0-1)\n• Flag ambiguous notes\n==========================================\nOUTPUT:\n[1] ABC NOTATION (copy-paste MIDI-ready)\n[2] PLAIN TEXT (PDF-printable)\n==========================================`}
(function(){
const nav=document.querySelector(".nav");
const tb=document.createElement("button");
tb.className="tab";tb.dataset.view="transcribe";tb.textContent="🎼 Transcribe";
nav.appendChild(tb);tb.addEventListener("click",()=>show("transcribe"));
const main=document.querySelector(".container");
const sec=document.createElement("section");
sec.className="view hidden";sec.id="view-transcribe";
sec.innerHTML=`<div class="card"><h2>🌍 World Music Transcriber</h2><p class="muted">Koi bhi YouTube/audio link dalo — full analysis prompt milega</p><form id="tForm" class="form"><div class="row"><label>🔗 URL</label><input name="url" placeholder="https://youtube.com/watch?v=..." required/></div><div class="row"><label>🎵 Genre</label><select name="gp" id="tGenre">${transcribePresets.map(p=>`<option value="${p.id}">${p.label}</option>`).join("")}</select></div><div class="row"><label>🎸 Instruments</label><input name="inst" id="tInst" placeholder="Auto-fill"/></div><div class="row"><label>🎹 Key</label><input name="key" placeholder="e.g. C major / Auto-detect"/></div><div class="row"><label>🥁 Tempo</label><input name="tempo" placeholder="Auto-detect BPM"/></div><div class="actions"><button class="btn" type="submit">⚡ Generate Prompt</button></div></form></div><div class="card" id="tOut" style="display:none"><h2>📋 Transcription Prompt</h2><textarea id="tText" class="out" rows="22" readonly></textarea><div class="actions"><button class="btn" id="tCopy">📋 Copy Prompt</button><button class="btn ghost" id="tPDF">🖨️ Save as PDF</button></div><p class="muted small">👆 Kisi bhi AI (ChatGPT/Gemini/Claude) me paste karo — full transcription milegi!</p></div>`;
main.appendChild(sec);
document.getElementById("tGenre").addEventListener("change",function(){const p=transcribePresets.find(x=>x.id===this.value);if(p)document.getElementById("tInst").value=p.instruments});
document.getElementById("tInst").value=transcribePresets[0].instruments;
document.getElementById("tForm").addEventListener("submit",(e)=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target).entries());const p=transcribePresets.find(x=>x.id===d.gp);const prompt=buildTranscribePrompt(d.url,p?p.genre:d.gp,d.inst,d.key,d.tempo);document.getElementById("tText").value=prompt;document.getElementById("tOut").style.display="block"});
document.getElementById("tCopy").addEventListener("click",async()=>{await navigator.clipboard.writeText(document.getElementById("tText").value);alert("Copied!")});
document.getElementById("tPDF").addEventListener("click",()=>{const t=document.getElementById("tText").value;const w=window.open("","_blank");w.document.write(`<html><head><title>Music Transcription</title><style>body{font-family:monospace;padding:24px;white-space:pre-wrap;font-size:13px;line-height:1.6}</style></head><body>${t.replace(/&/g,"&amp;").replace(/</g,"&lt;")}</body></html>`);w.document.close();w.print()});
})();
show("home");
